#!/usr/bin/perl -w

use strict;
use Test::Harness;
$Test::Harness::verbose = shift
  if $ARGV[0] and ($ARGV[0] =~ /^\d+$/ || $ARGV[0] eq "-v");

# This script runs Test::Harness on the tests found under the
# "t" directory. (stolen and adapted from LWP)

# First we check if we already are within the "t" directory
unless (-d "local") {
    chdir "t" or die "Can't chdir: $!";    # try to move into test directory

    # fix all relative library locations
    foreach (@INC) {
        $_ = "../$_" unless m,^/,;
    }
}
unshift(@INC, "../blib/lib", "../blib/arch");  # Pick up libs from ../blib directory
#print "\@INC:\n", map {"\t$_\n"} @INC;

my @tests;

if (@ARGV) {
    for (@ARGV) {
        if (-d $_) {
            push(@tests, <$_/*.t>);
        } else {
            $_ .= ".t" unless /\.t$/;
            push(@tests, $_);
        }
    }
} else {
    @tests = (<local/*.t>, <robot/*.t>);
    push(@tests,  <live/*.t>) if -f "live/ENABLED";
}

$ENV{PERL_LWP_TEST_ENGINE} = 'LWP::Parallel::UserAgent';
runtests @tests;
